name: CI

on:
  push:
    branches: ['main']

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          NODE_SERVER: true
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          envs: DATABASE_URL,FIREBASE_SERVICE_ACCOUNT_KEY,NODE_SERVER
          script: |
            git clone https://github.com/luanbt21/bayquamon.git
            cd bayquamon
            git pull origin main
            pnpm install --prefer-offline --frozen-lockfile
            pnpm build
            pm2 restart bayquamon
